service: pp-coord-test

servers:
  web:
    hosts:
      - 10.8.0.1
    options:
      publish:
        - '6002:6002'

proxy:
  ssl: true
  host: test-coordinate.pitchperfect.eu.com
  app_port: 6002
  healthcheck:
    path: /health
    timeout: 10
    interval: 2

env:
  clear:
    PORT: 6002
    API_URL: https://test-api.pitchperfect.eu.com
