service: pp-coord-dev

env:
  clear:
    PP_DATABASE: '<%= ENV["PP_DATABASE"] %>'
    PP_HST: '<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'
    PP_USR: '<%= ENV["PP_USR_DEV"] %>'
    PP_PORT_API: '<%= ENV["PP_PORT_API"] %>'
    API_URL: 'http://<%= ENV["PP_HOSTNAME_SSH_DEV"] %>:<%= ENV["PP_PORT_API_DEV"] %>'
    PORT: '<%= ENV["PP_PORT_COORD_DEV"] %>'

servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'
    options:
      publish:
        - '<%= ENV["PP_PORT_COORD_DEV"] %>:<%= ENV["PP_PORT_COORD"] %>'
ssh:
  user: '<%= ENV["PP_USR_SSH_DEV"] %>'

# dev: no TLS; unique proxy host to avoid conflicts with prod
proxy:
  host: dev-coord.pitchperfect.eu.com
  ssl: false
  app_port: <%= ENV["PP_PORT_COORD_DEV"] %>
  healthcheck:
    path: /health
    timeout: 10
    interval: 2

builder:
  dockerfile: ./Dockerfile
  local: false
  arch: arm64
  remote: 'ssh://<%= ENV["PP_USR_SSH_DEV"] %>@<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'




