service: pp-coord-dev

env:
  clear:
    PP_HST: '<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'
    PP_USR: '<%= ENV["PP_USR_DEV"] %>'
    API_URL: 'http://<%= ENV["PP_HOSTNAME_SSH_DEV"] %>:<%= ENV["PP_PORT_API_DEV"] %>'

servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'
    options:
      publish:
        - '<%= ENV["PP_PORT_COORD_DEV"] %>:<%= ENV["PP_PORT_COORD"] %>'
ssh:
  user: '<%= ENV["PP_USR_SSH_DEV"] %>'

# dev: no TLS; unique proxy host to avoid conflicts with prod
proxy:
  host: dev-coordinate.pitchperfect.eu.com
  ssl: false

builder:
  arch: arm64
  remote: 'ssh://<%= ENV["PP_USR_SSH_DEV"] %>@<%= ENV["PP_HOSTNAME_SSH_DEV"] %>'




