service: pp-coord-prd

env:
  clear:
    PP_HST: '<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'
    PP_USR: '<%= ENV["PP_USR_PRD"] %>'
    API_URL: 'http://<%= ENV["PP_HOSTNAME_SSH_PRD"] %>:<%= ENV["PP_PORT_API_PRD"] %>'

servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'
    options:
      publish:
        - '<%= ENV["PP_PORT_COORD_PRD"] %>:<%= ENV["PP_PORT_COORD"] %>'

ssh:
  user: '<%= ENV["PP_USR_SSH_PRD"] %>'

proxy:
  host: coordinate.pitchperfect.eu.com
  ssl: true

builder:
  arch: amd64
  remote: 'ssh://<%= ENV["PP_USR_SSH_PRD"] %>@<%= ENV["PP_HOSTNAME_SSH_PRD"] %>'

